server:
  port: 8181
kafka.servers: 192.168.146.54:9092
apiai.token: 
mongodb:
  host: 192.168.146.54
  port: 27017
  username: admin
  pass: admin
  welliedbname: wellie
  facilitatordbname: facilitator
  providerdbname:
    provider1: provider
    provider2: prov_db_2
logging.level.org.springframework.web: DEBUG
logging.file: ./welloculus-api-gateway.log